package com.hust.project3.gamequestionsanswer.constant

enum class MessageKey(val key: String) {
    SUCCESS("success"),
    FAILURE("failure"),
    REGISTER_ACCOUNT_EXISTED("failure_register_account_existed"),
    LOGIN_ACCOUNT_EXISTED("failure_login_account_existed"),
    LOGIN_ACCOUNT_NOT_EXISTED("failure_login_account_notExisted"),
    LOGIN_USERNAME_WRONG("failure_login_username_invalid"),
    PASSWORD_INVALID("failure_login_password_invalid"),
    REQUEST_TOKEN_INVALID_OR_NOT_AVAILABLE("failure_token_invalidOrNotAvailable"),
    REQUEST_TOKEN_EXPIRED("failure_token_expired"),
    REQUEST_TOKEN_WRONG("failure_token_invalidStructure"),
    REQUEST_TOKEN_REQUIRED("failure_token_required"),
    VERSION_INFO_INVALID("failure_version_infoInvalid"),
    VERSION_VERSIONING_INVALID("failure_version_versioningInvalid"),
    VERSION_OLD("failure_version_old"),
    VERSION_LATEST("success_version_latest"),
    VERSION_APP_TYPE_INVALID("failure_version_appTypeInvalid"),
    LOGIN_PASSWORD_WRONG("failure_login_password_invalid"),
//    MATCHING_PLAYER_WAITING("success_matchingPlayerWaiting"),
//    MATCHING_PLAYER_MATCHED("success_matchingPlayerMatched"),
    PLAYER_LEAVE_ROOM_SUCCESS("success_player_leaveRoom"),
    ROOM_HOST_LEAVE_ROOM_SUCCESS("success_room_host_wasLeavingRoom"),
//    COMPETITOR_LEAVE_ROOM_SUCCESS("success_competitor_wasLeavingRoom"),
//    PLAYER_READY("success_player_isReady"),
    SWITCH_LEVEL_TO_MIDDLE("success_questionLevel_switchToMiddle"),
    SWITCH_LEVEL_TO_ENDGAME("success_questionLevel_switchToEndgame"),
    MATCH_FINISH("success_match_isFinish"),
    SEND_RESULT_ANSWER_TO_PLAYER("success_sendResultAnswerToPlayer"),
    MATCH_CANCELED_BY_PLAYER_NOT_REQUEST("success_match_isCanceledByPlayerNotRequest"),
    PLAYER_REQUIRE_LOSE("success_playerRequireLose"),
    PLAYER_DISCONNECT_NETWORK("failure_player_disconnectNetwork")
}
